"""Fact bank backing the synthetic trace generator.

Every entry has a correct `answer` and a pre-authored `bad_answer` -- a
plausible-sounding but factually wrong claim that contradicts or is
unsupported by `context`. Both were written for every fact up front, before
any selection of which facts become "bad" traces and before any judge run,
so the hallucinated answers are not tuned to whatever the judge does or does
not catch.

14 domains x 5 facts = 70 facts, so `generate_synthetic_traces.py`'s
context-swap offset (half the bank size) always crosses into a different
domain.
"""

from __future__ import annotations

FACTS: list[dict[str, str]] = [
    # --- Geography ---
    {
        "domain": "geography",
        "question": "What is the capital of France?",
        "context": "France's capital city is Paris, located on the Seine river in the north of the country.",
        "answer": "Paris is the capital of France.",
        "bad_answer": "Lyon is the capital of France.",
    },
    {
        "domain": "geography",
        "question": "What is the longest river in the world?",
        "context": "The Nile River, flowing through northeastern Africa, is generally considered the longest river in the world at approximately 6,650 kilometers.",
        "answer": "The Nile is the longest river in the world, at about 6,650 kilometers.",
        "bad_answer": "The Amazon River is the longest river in the world, at about 6,650 kilometers.",
    },
    {
        "domain": "geography",
        "question": "Which desert is the largest hot desert on Earth?",
        "context": "The Sahara Desert in North Africa is the largest hot desert on Earth, covering roughly 9.2 million square kilometers.",
        "answer": "The Sahara Desert is the largest hot desert on Earth.",
        "bad_answer": "The Gobi Desert is the largest hot desert on Earth.",
    },
    {
        "domain": "geography",
        "question": "What is the smallest country in the world by area?",
        "context": "Vatican City, an independent city-state enclaved within Rome, is the smallest country in the world by area at about 0.49 square kilometers.",
        "answer": "Vatican City is the smallest country in the world by area.",
        "bad_answer": "Monaco is the smallest country in the world by area.",
    },
    {
        "domain": "geography",
        "question": "What mountain is the tallest above sea level?",
        "context": "Mount Everest, located in the Himalayas on the border of Nepal and China, stands at 8,849 meters above sea level, making it the tallest mountain above sea level.",
        "answer": "Mount Everest is the tallest mountain above sea level, at 8,849 meters.",
        "bad_answer": "K2 is the tallest mountain above sea level, at 8,849 meters.",
    },
    # --- Physics ---
    {
        "domain": "physics",
        "question": "What is the speed of light in a vacuum?",
        "context": "Light travels through a vacuum at a constant speed of approximately 299,792 kilometers per second.",
        "answer": "The speed of light in a vacuum is about 299,792 kilometers per second.",
        "bad_answer": "The speed of light in a vacuum is about 150,000 kilometers per second.",
    },
    {
        "domain": "physics",
        "question": "Who formulated the theory of general relativity?",
        "context": "Albert Einstein published his theory of general relativity in 1915, describing gravity as the curvature of spacetime.",
        "answer": "Albert Einstein formulated the theory of general relativity.",
        "bad_answer": "Isaac Newton formulated the theory of general relativity.",
    },
    {
        "domain": "physics",
        "question": "What is Newton's second law of motion?",
        "context": "Newton's second law states that the force acting on an object equals its mass multiplied by its acceleration, expressed as F = ma.",
        "answer": "Newton's second law states that force equals mass times acceleration.",
        "bad_answer": "Newton's second law states that force equals mass divided by acceleration.",
    },
    {
        "domain": "physics",
        "question": "What particle is responsible for carrying the electromagnetic force?",
        "context": "The photon is the elementary particle that carries the electromagnetic force and has no mass.",
        "answer": "The photon carries the electromagnetic force.",
        "bad_answer": "The electron carries the electromagnetic force.",
    },
    {
        "domain": "physics",
        "question": "At what temperature does water freeze at standard atmospheric pressure?",
        "context": "At standard atmospheric pressure, water freezes at 0 degrees Celsius (32 degrees Fahrenheit).",
        "answer": "Water freezes at 0 degrees Celsius at standard atmospheric pressure.",
        "bad_answer": "Water freezes at -10 degrees Celsius at standard atmospheric pressure.",
    },
    # --- Chemistry ---
    {
        "domain": "chemistry",
        "question": "What is the chemical symbol for gold?",
        "context": "Gold, a dense yellow metal prized since antiquity, has the chemical symbol Au, derived from the Latin word aurum.",
        "answer": "The chemical symbol for gold is Au.",
        "bad_answer": "The chemical symbol for gold is Ag.",
    },
    {
        "domain": "chemistry",
        "question": "What gas do plants absorb from the atmosphere for photosynthesis?",
        "context": "During photosynthesis, plants absorb carbon dioxide from the atmosphere and use sunlight to convert it into glucose and oxygen.",
        "answer": "Plants absorb carbon dioxide for photosynthesis.",
        "bad_answer": "Plants absorb oxygen from the atmosphere for photosynthesis.",
    },
    {
        "domain": "chemistry",
        "question": "What is the most abundant gas in Earth's atmosphere?",
        "context": "Nitrogen makes up about 78 percent of Earth's atmosphere by volume, making it the most abundant gas present.",
        "answer": "Nitrogen is the most abundant gas in Earth's atmosphere.",
        "bad_answer": "Oxygen is the most abundant gas in Earth's atmosphere.",
    },
    {
        "domain": "chemistry",
        "question": "What is the pH value of a neutral solution at 25 degrees Celsius?",
        "context": "At 25 degrees Celsius, a neutral aqueous solution has a pH of 7, meaning it is neither acidic nor basic.",
        "answer": "A neutral solution has a pH of 7 at 25 degrees Celsius.",
        "bad_answer": "A neutral solution has a pH of 0 at 25 degrees Celsius.",
    },
    {
        "domain": "chemistry",
        "question": "What element has the atomic number 1?",
        "context": "Hydrogen, the lightest and most abundant element in the universe, has an atomic number of 1.",
        "answer": "Hydrogen has atomic number 1.",
        "bad_answer": "Helium has atomic number 1.",
    },
    # --- Biology ---
    {
        "domain": "biology",
        "question": "What is the powerhouse of the cell?",
        "context": "Mitochondria generate most of a cell's supply of ATP, the energy currency of the cell, earning them the nickname 'powerhouse of the cell.'",
        "answer": "The mitochondria are known as the powerhouse of the cell.",
        "bad_answer": "The nucleus is known as the powerhouse of the cell.",
    },
    {
        "domain": "biology",
        "question": "How many chambers does the human heart have?",
        "context": "The human heart has four chambers: two atria and two ventricles, which work together to pump blood through the body.",
        "answer": "The human heart has four chambers.",
        "bad_answer": "The human heart has three chambers.",
    },
    {
        "domain": "biology",
        "question": "What is the process by which plants make their own food called?",
        "context": "Photosynthesis is the process by which green plants use sunlight, water, and carbon dioxide to synthesize their own food.",
        "answer": "Plants make their own food through photosynthesis.",
        "bad_answer": "Plants make their own food through a process called respiration.",
    },
    {
        "domain": "biology",
        "question": "What molecule carries genetic information in most living organisms?",
        "context": "Deoxyribonucleic acid, or DNA, carries the genetic instructions used in the growth, development, and functioning of most living organisms.",
        "answer": "DNA carries genetic information in most living organisms.",
        "bad_answer": "RNA carries the primary genetic information in most living organisms.",
    },
    {
        "domain": "biology",
        "question": "What is the largest organ in the human body?",
        "context": "The skin is the largest organ of the human body, covering an average surface area of about 1.8 square meters in adults.",
        "answer": "The skin is the largest organ in the human body.",
        "bad_answer": "The liver is the largest organ in the human body.",
    },
    # --- Astronomy ---
    {
        "domain": "astronomy",
        "question": "Which planet is known as the Red Planet?",
        "context": "Mars is often called the Red Planet because iron oxide, or rust, on its surface gives it a reddish appearance.",
        "answer": "Mars is known as the Red Planet.",
        "bad_answer": "Venus is known as the Red Planet.",
    },
    {
        "domain": "astronomy",
        "question": "What is the closest star to Earth?",
        "context": "The Sun is the closest star to Earth, located about 150 million kilometers away, and is the center of our solar system.",
        "answer": "The Sun is the closest star to Earth.",
        "bad_answer": "Proxima Centauri is the closest star to Earth.",
    },
    {
        "domain": "astronomy",
        "question": "How many planets are in our solar system?",
        "context": "Our solar system contains eight recognized planets, ranging from Mercury, closest to the Sun, to Neptune, the farthest.",
        "answer": "There are eight planets in our solar system.",
        "bad_answer": "There are nine planets in our solar system.",
    },
    {
        "domain": "astronomy",
        "question": "What galaxy is Earth located in?",
        "context": "Earth is located within the Milky Way galaxy, a barred spiral galaxy containing hundreds of billions of stars.",
        "answer": "Earth is located in the Milky Way galaxy.",
        "bad_answer": "Earth is located in the Andromeda galaxy.",
    },
    {
        "domain": "astronomy",
        "question": "What was the first artificial satellite launched into space?",
        "context": "Sputnik 1, launched by the Soviet Union in 1957, was the first artificial satellite to orbit Earth.",
        "answer": "Sputnik 1 was the first artificial satellite launched into space.",
        "bad_answer": "Explorer 1 was the first artificial satellite launched into space.",
    },
    # --- History ---
    {
        "domain": "history",
        "question": "In what year did World War II end?",
        "context": "World War II ended in 1945 following the surrender of Germany in May and Japan in September of that year.",
        "answer": "World War II ended in 1945.",
        "bad_answer": "World War II ended in 1943.",
    },
    {
        "domain": "history",
        "question": "Who was the first President of the United States?",
        "context": "George Washington served as the first President of the United States, taking office in 1789.",
        "answer": "George Washington was the first President of the United States.",
        "bad_answer": "Thomas Jefferson was the first President of the United States.",
    },
    {
        "domain": "history",
        "question": "What ancient civilization built the pyramids of Giza?",
        "context": "The pyramids of Giza were constructed by the ancient Egyptians as tombs for their pharaohs, primarily during the Fourth Dynasty.",
        "answer": "The ancient Egyptians built the pyramids of Giza.",
        "bad_answer": "The Roman Empire built the pyramids of Giza.",
    },
    {
        "domain": "history",
        "question": "What year did the Berlin Wall fall?",
        "context": "The Berlin Wall fell in November 1989, marking a major turning point that led to German reunification.",
        "answer": "The Berlin Wall fell in 1989.",
        "bad_answer": "The Berlin Wall fell in 1991.",
    },
    {
        "domain": "history",
        "question": "Who wrote the Declaration of Independence?",
        "context": "Thomas Jefferson was the principal author of the United States Declaration of Independence, adopted in 1776.",
        "answer": "Thomas Jefferson was the principal author of the Declaration of Independence.",
        "bad_answer": "Benjamin Franklin was the principal author of the Declaration of Independence.",
    },
    # --- Literature ---
    {
        "domain": "literature",
        "question": "Who wrote the novel 'Pride and Prejudice'?",
        "context": "Pride and Prejudice is a novel written by Jane Austen, first published in 1813.",
        "answer": "Jane Austen wrote Pride and Prejudice.",
        "bad_answer": "Charlotte Bronte wrote Pride and Prejudice.",
    },
    {
        "domain": "literature",
        "question": "Who is the author of the 'Harry Potter' book series?",
        "context": "The Harry Potter series was written by British author J.K. Rowling, with the first book published in 1997.",
        "answer": "J.K. Rowling is the author of the Harry Potter series.",
        "bad_answer": "Roald Dahl is the author of the Harry Potter series.",
    },
    {
        "domain": "literature",
        "question": "Who created the fictional detective Sherlock Holmes?",
        "context": "Arthur Conan Doyle created the detective character Sherlock Holmes, who first appeared in print in 1887.",
        "answer": "Arthur Conan Doyle created the detective Sherlock Holmes.",
        "bad_answer": "Agatha Christie created the detective Sherlock Holmes.",
    },
    {
        "domain": "literature",
        "question": "Who wrote the play 'Romeo and Juliet'?",
        "context": "Romeo and Juliet is a tragedy written by William Shakespeare early in his career, believed to have been written around 1594-1596.",
        "answer": "William Shakespeare wrote Romeo and Juliet.",
        "bad_answer": "Christopher Marlowe wrote the play Romeo and Juliet.",
    },
    {
        "domain": "literature",
        "question": "What dystopian novel by George Orwell introduced the concept of 'Big Brother'?",
        "context": "George Orwell's novel Nineteen Eighty-Four, published in 1949, introduced the concept of Big Brother as a symbol of totalitarian surveillance.",
        "answer": "George Orwell's Nineteen Eighty-Four introduced the concept of Big Brother.",
        "bad_answer": "Aldous Huxley's novel introduced the concept of Big Brother.",
    },
    # --- Technology ---
    {
        "domain": "technology",
        "question": "Who is credited with inventing the World Wide Web?",
        "context": "Tim Berners-Lee, a British computer scientist, is credited with inventing the World Wide Web in 1989 while working at CERN.",
        "answer": "Tim Berners-Lee invented the World Wide Web.",
        "bad_answer": "Vint Cerf is credited with inventing the World Wide Web.",
    },
    {
        "domain": "technology",
        "question": "What does CPU stand for?",
        "context": "CPU stands for Central Processing Unit, the primary component of a computer that executes instructions.",
        "answer": "CPU stands for Central Processing Unit.",
        "bad_answer": "CPU stands for Computer Processing Utility.",
    },
    {
        "domain": "technology",
        "question": "What programming language was created by Guido van Rossum?",
        "context": "Python is a high-level programming language created by Guido van Rossum and first released in 1991.",
        "answer": "Guido van Rossum created the Python programming language.",
        "bad_answer": "James Gosling created the Python programming language.",
    },
    {
        "domain": "technology",
        "question": "What company developed the Android operating system?",
        "context": "Android is a mobile operating system that was primarily developed by Google, with the first commercial version released in 2008.",
        "answer": "Google developed the Android operating system.",
        "bad_answer": "Apple developed the Android operating system.",
    },
    {
        "domain": "technology",
        "question": "What does HTTP stand for?",
        "context": "HTTP stands for Hypertext Transfer Protocol, the foundational protocol used for transmitting data over the World Wide Web.",
        "answer": "HTTP stands for Hypertext Transfer Protocol.",
        "bad_answer": "HTTP stands for Hyper Transfer Text Protocol.",
    },
    # --- Mathematics ---
    {
        "domain": "mathematics",
        "question": "What is the value of pi rounded to two decimal places?",
        "context": "Pi, the ratio of a circle's circumference to its diameter, is approximately 3.14159, or 3.14 when rounded to two decimal places.",
        "answer": "Pi is approximately 3.14 when rounded to two decimal places.",
        "bad_answer": "Pi is approximately 4.13 when rounded to two decimal places.",
    },
    {
        "domain": "mathematics",
        "question": "What is the sum of the interior angles of a triangle?",
        "context": "In Euclidean geometry, the interior angles of any triangle always sum to 180 degrees.",
        "answer": "The interior angles of a triangle sum to 180 degrees.",
        "bad_answer": "The interior angles of a triangle sum to 270 degrees.",
    },
    {
        "domain": "mathematics",
        "question": "What is the square root of 144?",
        "context": "144 is a perfect square, and its square root is 12, since 12 multiplied by 12 equals 144.",
        "answer": "The square root of 144 is 12.",
        "bad_answer": "The square root of 144 is 14.",
    },
    {
        "domain": "mathematics",
        "question": "What do you call a number that is only divisible by 1 and itself?",
        "context": "A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself.",
        "answer": "A number divisible only by 1 and itself is called a prime number.",
        "bad_answer": "A number divisible only by 1 and itself is called a composite number.",
    },
    {
        "domain": "mathematics",
        "question": "What is the mathematical constant approximately equal to 2.71828 called?",
        "context": "Euler's number, denoted e, is a mathematical constant approximately equal to 2.71828, widely used in calculus.",
        "answer": "The constant approximately equal to 2.71828 is called Euler's number, e.",
        "bad_answer": "The mathematical constant approximately equal to 2.71828 is called pi.",
    },
    # --- Medicine ---
    {
        "domain": "medicine",
        "question": "What organ is primarily responsible for filtering blood and producing urine?",
        "context": "The kidneys filter waste products and excess fluid from the blood, producing urine as a byproduct.",
        "answer": "The kidneys are primarily responsible for filtering blood and producing urine.",
        "bad_answer": "The liver is primarily responsible for filtering blood and producing urine.",
    },
    {
        "domain": "medicine",
        "question": "What vitamin is primarily produced when skin is exposed to sunlight?",
        "context": "When skin is exposed to ultraviolet sunlight, the body synthesizes vitamin D, which supports bone health.",
        "answer": "Vitamin D is primarily produced when skin is exposed to sunlight.",
        "bad_answer": "Vitamin C is primarily produced when skin is exposed to sunlight.",
    },
    {
        "domain": "medicine",
        "question": "What is the normal resting heart rate range for a healthy adult?",
        "context": "A healthy adult's resting heart rate typically ranges between 60 and 100 beats per minute.",
        "answer": "A healthy adult's normal resting heart rate is between 60 and 100 beats per minute.",
        "bad_answer": "A healthy adult's normal resting heart rate is between 120 and 160 beats per minute.",
    },
    {
        "domain": "medicine",
        "question": "What blood type is considered the universal donor?",
        "context": "Type O negative blood is considered the universal donor type because it lacks A, B, and Rh antigens, making it compatible with most recipients.",
        "answer": "Type O negative blood is considered the universal donor.",
        "bad_answer": "Type AB positive blood is considered the universal donor.",
    },
    {
        "domain": "medicine",
        "question": "What disease is caused by a deficiency of insulin or insulin resistance?",
        "context": "Diabetes mellitus is a chronic condition caused by insufficient insulin production or the body's resistance to insulin, leading to high blood sugar levels.",
        "answer": "Diabetes is caused by insufficient insulin or insulin resistance.",
        "bad_answer": "Diabetes is caused by an excess of insulin production.",
    },
    # --- Economics ---
    {
        "domain": "economics",
        "question": "What economic term describes a sustained increase in the general price level?",
        "context": "Inflation refers to a sustained increase in the general price level of goods and services in an economy over time.",
        "answer": "Inflation describes a sustained increase in the general price level.",
        "bad_answer": "Inflation refers to a sustained decrease in the general price level.",
    },
    {
        "domain": "economics",
        "question": "Who wrote 'The Wealth of Nations'?",
        "context": "The Wealth of Nations, published in 1776, was written by Scottish economist Adam Smith and is considered a foundational text of classical economics.",
        "answer": "Adam Smith wrote The Wealth of Nations.",
        "bad_answer": "Karl Marx wrote The Wealth of Nations.",
    },
    {
        "domain": "economics",
        "question": "What term describes the total value of goods and services produced in a country in a year?",
        "context": "Gross Domestic Product, or GDP, measures the total monetary value of all goods and services produced within a country's borders in a given year.",
        "answer": "GDP measures the total value of goods and services produced in a country in a year.",
        "bad_answer": "GDP measures the total population of a country in a given year.",
    },
    {
        "domain": "economics",
        "question": "What is the law of supply and demand?",
        "context": "The law of supply and demand describes how the price of a good is determined by the balance between how much of it is available and how much people want it.",
        "answer": "The law of supply and demand describes how price is determined by availability and desire for a good.",
        "bad_answer": "The law of supply and demand states that price is determined solely by government regulation.",
    },
    {
        "domain": "economics",
        "question": "What institution sets monetary policy in the United States?",
        "context": "The Federal Reserve is the central banking system of the United States and is responsible for setting the country's monetary policy.",
        "answer": "The Federal Reserve sets monetary policy in the United States.",
        "bad_answer": "The United States Treasury sets monetary policy in the United States.",
    },
    # --- Law ---
    {
        "domain": "law",
        "question": "What document is considered the supreme law of the United States?",
        "context": "The United States Constitution, ratified in 1788, is considered the supreme law of the land in the United States.",
        "answer": "The United States Constitution is the supreme law of the United States.",
        "bad_answer": "The Magna Carta is the supreme law of the United States.",
    },
    {
        "domain": "law",
        "question": "What is the term for a legal document that states how a person's property should be distributed after death?",
        "context": "A will is a legal document that specifies how a person's property and assets should be distributed after their death.",
        "answer": "A will specifies how a person's property should be distributed after death.",
        "bad_answer": "A deed is the legal document that specifies how a person's property should be distributed after death.",
    },
    {
        "domain": "law",
        "question": "What amendment to the U.S. Constitution abolished slavery?",
        "context": "The Thirteenth Amendment to the United States Constitution, ratified in 1865, abolished slavery and involuntary servitude.",
        "answer": "The Thirteenth Amendment abolished slavery in the United States.",
        "bad_answer": "The Nineteenth Amendment abolished slavery in the United States.",
    },
    {
        "domain": "law",
        "question": "What is the presumption a defendant is entitled to in a criminal trial?",
        "context": "In most legal systems, a defendant is presumed innocent until proven guilty beyond a reasonable doubt.",
        "answer": "A defendant is presumed innocent until proven guilty.",
        "bad_answer": "A defendant is presumed guilty until proven innocent.",
    },
    {
        "domain": "law",
        "question": "What international agreement, adopted in 1948, outlines fundamental human rights?",
        "context": "The Universal Declaration of Human Rights, adopted by the United Nations General Assembly in 1948, outlines fundamental rights to be universally protected.",
        "answer": "The Universal Declaration of Human Rights, adopted in 1948, outlines fundamental human rights.",
        "bad_answer": "The Universal Declaration of Human Rights was adopted in 1918.",
    },
    # --- Sports ---
    {
        "domain": "sports",
        "question": "How many players are on a standard soccer team on the field at once?",
        "context": "A standard soccer team fields eleven players at a time, including one goalkeeper.",
        "answer": "A standard soccer team has eleven players on the field at once.",
        "bad_answer": "A standard soccer team fields nine players on the field at once.",
    },
    {
        "domain": "sports",
        "question": "In what country did the modern Olympic Games originate?",
        "context": "The modern Olympic Games were revived in Athens, Greece in 1896, inspired by the ancient Olympic Games held in ancient Greece.",
        "answer": "The modern Olympic Games originated in Greece.",
        "bad_answer": "The modern Olympic Games originated in Italy.",
    },
    {
        "domain": "sports",
        "question": "How many points is a touchdown worth in American football?",
        "context": "In American football, a touchdown is worth six points, with an additional point or two available afterward.",
        "answer": "A touchdown is worth six points in American football.",
        "bad_answer": "A touchdown is worth ten points in American football.",
    },
    {
        "domain": "sports",
        "question": "What sport is known as 'the beautiful game'?",
        "context": "Association football, commonly known as soccer, is often referred to as 'the beautiful game' due to its global popularity and fluid style of play.",
        "answer": "Soccer is known as 'the beautiful game.'",
        "bad_answer": "Basketball is known as 'the beautiful game.'",
    },
    {
        "domain": "sports",
        "question": "How many rings are on the Olympic flag?",
        "context": "The Olympic flag features five interlocking rings, representing the union of the five inhabited continents.",
        "answer": "The Olympic flag has five interlocking rings.",
        "bad_answer": "The Olympic flag has seven interlocking rings.",
    },
    # --- Food & Cooking ---
    {
        "domain": "food",
        "question": "What is the main ingredient in traditional guacamole?",
        "context": "Traditional guacamole is made primarily from mashed avocados, often mixed with lime juice, salt, and onion.",
        "answer": "The main ingredient in traditional guacamole is avocado.",
        "bad_answer": "The main ingredient in traditional guacamole is tomato.",
    },
    {
        "domain": "food",
        "question": "What process turns grape juice into wine?",
        "context": "Fermentation, a process in which yeast converts sugars into alcohol, is what turns grape juice into wine.",
        "answer": "Fermentation turns grape juice into wine.",
        "bad_answer": "Distillation is what turns grape juice into wine.",
    },
    {
        "domain": "food",
        "question": "What spice is derived from the Crocus flower and is one of the most expensive by weight?",
        "context": "Saffron, derived from the stigmas of the Crocus sativus flower, is one of the most expensive spices in the world by weight.",
        "answer": "Saffron, derived from the Crocus flower, is one of the most expensive spices by weight.",
        "bad_answer": "Vanilla, derived from the Crocus flower, is one of the most expensive spices in the world by weight.",
    },
    {
        "domain": "food",
        "question": "What Italian dish consists of a flat dough base typically topped with tomato sauce and cheese?",
        "context": "Pizza is a traditional Italian dish made from a flattened dough base, typically topped with tomato sauce, cheese, and various other ingredients.",
        "answer": "Pizza is an Italian dish made of a dough base topped with tomato sauce and cheese.",
        "bad_answer": "Pizza is a traditional French dish made of a dough base topped with tomato sauce and cheese.",
    },
    {
        "domain": "food",
        "question": "What gives sourdough bread its distinctive tangy flavor?",
        "context": "Sourdough bread gets its distinctive tangy flavor from the wild yeast and lactic acid bacteria present in its natural fermentation starter.",
        "answer": "The wild yeast and lactic acid bacteria in the fermentation starter give sourdough bread its tangy flavor.",
        "bad_answer": "Added sugar gives sourdough bread its distinctive tangy flavor.",
    },
]
